name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: python -m unittest discover -s tests -p "tests_*.py" -v

      - name: Build Docker image
        run: docker build -t hello-secure-world:${{ github.sha }} .

      - name: Smoke-test container
        run: |
          # run your image and check it prints the expected message
          docker run --rm hello-secure-world:${{ github.sha }} \
            python -u app/main.py \
            | grep "Hello, Secure World!"

      - name: Debug Docker Hub creds
        run: |
          echo "Username: ${{ secrets.DOCKER_HUB_USERNAME }}"
          echo "Password length: ${#{{ secrets.DOCKER_HUB_PASSWORD }}}"


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push image
        run: |
          docker tag hello-secure-world:${{ github.sha }} \
                  ${{ secrets.DOCKER_HUB_USERNAME }}/hello-secure-world:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/hello-secure-world:latest

